incidentService:
  enabled: true
  replicaCount: 1

  image:
    repository: neeraj2806/incident
    tag: "v1"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5002

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  env:
    REDIS_PORT: "6379"
    REDIS_HOST: "redis-incident-service"

  livenessProbe:
    enabled: false
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10

  readinessProbe:
    enabled: false
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5

nameOverride: ""
fullnameOverride: "incident-service"

redisIncident:
  enabled: true
  replicaCount: 1

  image:
    repository: redis
    tag: "latest"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 6379

  persistence:
    enabled: true
    storageClass: "standard"
    size: 1Gi

  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

  livenessProbe:
    enabled: false
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10

  readinessProbe:
    enabled: false
    path: /
    initialDelaySeconds: 5
    periodSeconds: 5
